import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: 'Next 14 - ShadCn UI',
  description: 'Generated by create next app'
}

const myFont = localFont({
  src: [
    {
      path: './fonts/lexends/Lexend-Light.ttf',
      weight: '300'
    },
    {
      path: './fonts/lexends/Lexend-Regular.ttf',
      weight: '400'
    },
    {
      path: './fonts/lexends/Lexend-Medium.ttf',
      weight: '500'
    },
    {
      path: './fonts/lexends/Lexend-SemiBold.ttf',
      weight: '600'
    },
    {
      path: './fonts/lexends/Lexend-Bold.ttf',
      weight: '700'
    }
  ]
})

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link rel='icon' href='https://avatarfiles.alphacoders.com/300/thumb-1920-300266.png' sizes='any' />
        <link href='https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap' rel='stylesheet' />
      </head>
      <body className={myFont.className}>{children}</body>
    </html>
  )
}
